## Numpy Array - Numerical Pthon

In [ ]:
import numpy as np

In [ ]:
a=np.array([[1,2,3],[4,9,6],[7,8,5]])
a

In [ ]:
a.argmax()

In [ ]:
type(np.array(['Sumit',2,3]))

In [ ]:
#Upcasting
np.array([1,2,3.0])

In [ ]:
#Two Dimesnsion
np.array([[1,2],[3,4]])

In [ ]:
#Minimum Dimensions - Specifies the minimum number of dimensions that the resulting array should have.  
#Ones will be pre-pended to the shape as needed to meet this requirement.
np.array([1,2,3],ndmin=5)

In [ ]:
#dtype
np.array([1,2,3],dtype=complex)

In [ ]:
### Data-type consisting of more than one element: (Big Indane and little indane)
x=np.array([(1,2,3),(4,5,6)], dtype=[('a','<i2'),('b','<i4'),('c','<i8')])
x

In [ ]:
x['a']

In [ ]:
x['b'].dtype

In [ ]:
x['c']

In [ ]:
type(x[1][1])

In [ ]:
y=np.array([(1,2,3),(4,5,6)], dtype=[('a','<f2'),('b','<f4'),('c','<f8')])
y

In [ ]:
y['a']

In [ ]:
y['b']

In [ ]:
y['c'].dtype

In [ ]:
np.array([(1,2),(3,4)])

In [ ]:
np.mat(np.array([[1,2],[3,4]]))

In [ ]:
np.mat([[1,2],[3,4]])

In [ ]:
np.mat('1 2;3 4')

In [ ]:
type(np.mat('1 2;3 4'))

Matrix is a sub-class of array inside numpy

In [ ]:
a = np.mat('1 2;3 4')
a.shape

In [ ]:
a

In [ ]:
a[0,1]

In [ ]:
a[0][0]

### numpy.asarray

numpy.ararray converts the input into an array or the list into an array

In [ ]:
a=[1,2]
type(a)

In [ ]:
b=np.asarray(a)
b

In [ ]:
type(b)

1. When input is a list then both np.array and np.asarray gives the same output

In [ ]:
a = [[1,2,3],[4,5,6],[7,8,9]]
b = np.array(a)
c = np.asarray(a)
print('a = \n', a)
print('b = \n', b)
print('c = \n', c)

In [ ]:
print(b is a)
print(c is a)

From this we can see that np.array is the same as np.asarray, which converts the input into a matrix format. When the input is a list, changing the value of the list does not affect the value converted to the matrix.

2. When input is an array

In [ ]:
a = np.random.random((3,3))
print(a.dtype)
print(type(a))
b = np.array(a, dtype='float64')
c = np.array(a, dtype='float64')
print('a = \n', a)
print('b = \n', b)
print('c = \n', c)

In [ ]:
print(b is a)
print(c is a)

In [ ]:
#If dtype is set, array is copied only if dtype does not match:

In [ ]:
a = np.array([1,2],dtype=np.float32)
a

In [ ]:
np.asarray([1,2]) is a

In [ ]:
np.asarray([1,2])

In [ ]:
np.asarray(a, dtype=np.float64) is a

In [ ]:
# ndarray subclasses are not passed through
issubclass(np.matrix,np.ndarray)

In [ ]:
issubclass(np.ndarray,np.matrix)

In [ ]:
a = np.matrix([[1,2]])
np.asanyarray(a)

In [ ]:
np.asarray(a) is a

In [ ]:
np.asanyarray(a) is a

In [ ]:
type(np.asanyarray(a))

In [ ]:
type(np.asarray(a))

In [ ]:
type(a)

### numpy.asanyarray

If something is already available in any form of array, then it will not try to convert that into array again. But if it is not an array then it will convert that into an array.

In [ ]:
a = [1,2]

In [ ]:
np.asanyarray(a)

In [ ]:
type(np.asanyarray(a))

In [ ]:
np.asanyarray(a) is a

In [ ]:
a = np.matrix([1,2])
a

In [ ]:
np.asanyarray(a)

In [ ]:
np.asanyarray(a) is a

In [ ]:
np.asanyarray([1,2]) is a

In [ ]:
np.array(a, copy=True)

Deep Copy and Shwallow copy

In [1]:
import numpy as np
x = np.array([1,2,3])
x

array([1, 2, 3])

In [2]:
y = x

In [3]:
x

array([1, 2, 3])

In [4]:
y

array([1, 2, 3])

In [5]:
y[0] = 10

In [6]:
y

array([10,  2,  3])

In [7]:
x

array([10,  2,  3])

In [14]:
id(x)

1902796624800

In [15]:
id(y)

1902796624800

In the above scenario, both x and y point to the same location. So if we change one element in the one of the array then the same will be reflected in the other one. This is called shwallow copy.

In [8]:
z = np.copy(x)

In [16]:
id(x) #print memory location of x

1902796624800

In [17]:
id(z) #print memory location of y

1902796574592

In [9]:
x

array([10,  2,  3])

In [10]:
z

array([10,  2,  3])

In [11]:
z[0]=5

In [12]:
z

array([5, 2, 3])

In [13]:
x

array([10,  2,  3])

In the above case where we use the method copy from numpy to copy an array then the new array will be created in a different new memory location. So in this case if change any element in one of the array, the same will not be reflected in the other array. It is called as deep copy.

### numpy.fromfunction

In [18]:
#Construct an array by executing a function over each coordinate.

In [21]:
np.fromfunction(lambda i,j:i!=j,(3,3),dtype=int)

array([[False,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [23]:
np.fromfunction(lambda i,j:i+j,(3,3),dtype=int)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [44]:
#Create a new 1-dimensional array from an iterable object.
iterable = [x*x for x in range(5)]
iterable

[0, 1, 4, 9, 16]

In [45]:
iterable = (x*x for x in range(5))
iterable

<generator object <genexpr> at 0x000001BB0A55CAC8>

In [52]:
np.fromiter(iterable,dtype=int,count=2)# By default count is -1, that means all the elements in iterable is read.

array([0, 1])

In [51]:
np.array(range(5))

array([0, 1, 2, 3, 4])

In [54]:
np.array(list(range(5)))

array([0, 1, 2, 3, 4])

In [42]:
a = np.fromstring('123 234 345 456 567',sep=' ',dtype=int, count=2)
a

array([123, 234])

In [43]:
# How to create create a record array from a (flat) list of arrays

In [46]:
x1=np.array([1,2,3,4])

In [47]:
x2=np.array(['a','dd','xyz','12'])

In [48]:
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [55]:
r = np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

### data types

In [63]:
my_list=[1,2,4]
arr = np.array(my_list)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[1 2 4]


In [64]:
arr.ndim

1

In [76]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print(mat)
print(mat.ndim)
print(mat.shape)
print(mat.size)
print(mat.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
9
int32


In [75]:
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array

Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


In [80]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print(mat)

[[1.1 2.  3. ]
 [4.  5.2 6. ]
 [7.  8.3 9. ]]


In [82]:
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")

Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [87]:
b = np.array([(1.5,2,3),(4,5,6),(7,8,9)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]
 [7.  8.  9. ]]


### arange and linspace

Difference between range and arange is, in case of range function we can't provide a floating point range. However incase of arnage function we can provide a floating point number.

In [88]:
list(range(5))

[0, 1, 2, 3, 4]

In [93]:
np.arange(2.0,7.0,1.5)

array([2. , 3.5, 5. , 6.5])

In [95]:
type(np.arange(5,9))

numpy.ndarray

In [96]:
print("A series of numbers:",type(np.arange(5,16)))
np.arange(5,16,2.3)# A series of numbers from low to high

A series of numbers: <class 'numpy.ndarray'>


array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [97]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [102]:
print("Numbers spaced apart by 2:",np.arange(50,0,-5)) # Numbers spaced apart by -5

Numbers spaced apart by 2: [50 45 40 35 30 25 20 15 10  5]


In [107]:
print("Every 5th number from 50 in reverse order\n",np.arange(50,-1,-5))

Every 5th number from 50 in reverse order
 [50 45 40 35 30 25 20 15 10  5  0]


In [108]:
type(np.arange(50,-1,-5))

numpy.ndarray

In [115]:
np.linspace(5,0,num=6,endpoint=False)

array([5.        , 4.16666667, 3.33333333, 2.5       , 1.66666667,
       0.83333333])

In [118]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,5,num=21)))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5. ]


### Matrix creation

In [124]:
#Vector of Zeros
print('Vector Of Zeror\n------------------------')
print(np.zeros(5))

Vector Of Zeror
------------------------
[0. 0. 0. 0. 0.]


In [125]:
print("Matrix of zeroes\n--------------------")
print(np.zeros([5,5],dtype=int))

Matrix of zeroes
--------------------
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [126]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((5,5),dtype=int))

Matrix of zeroes
--------------------
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [127]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [129]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2))) # Note matrix dimension specified by Tuples


Matrix of ones
---------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [131]:
print("Matrix of ones\n---------------------")
print(np.ones((3,4,2))) # Note matrix dimension specified by Tuples


Matrix of ones
---------------------
[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]]]


In [132]:
print("Matrix of 5's\n---------------------")
print(5*np.ones((3,5)))

Matrix of 5's
---------------------
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [137]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [134]:
print("Empty matrix\n-------------\n", np.empty((3,5)))

Empty matrix
-------------
 [[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]


In [138]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [139]:
type(np.empty((3,6)))

numpy.ndarray

In [142]:
#Identity Matrix creation
indentity = np.eye(6)
indentity

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [143]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [144]:
np.arange(3)

array([0, 1, 2])

In [145]:
np.arange(3.0)

array([0., 1., 2.])

In [146]:
 np.arange(3,7)

array([3, 4, 5, 6])

In [147]:
np.arange(3,7,2)

array([3, 5])

In [148]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [149]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [150]:
np.linspace(2.0, 3.0, num=9, retstep=True)

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [151]:
#Return numbers spaced evenly on a log scale.
np.linspace(2.0, 3.0, num=4)

array([2.        , 2.33333333, 2.66666667, 3.        ])

In [152]:
np.logspace(2.0, 3.0, num=4,base = 10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [153]:
np.logspace(2.0, 3.0, num=4, endpoint=False)

array([100.        , 177.827941  , 316.22776602, 562.34132519])

In [154]:
np.logspace(2.0, 3.0, num=4, base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [155]:
#Extract a diagonal or construct a diagonal array.

In [172]:
x = np.arange(16).reshape(-1,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [163]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [164]:
x.reshape(3,3,1)

array([[[0],
        [1],
        [2]],

       [[3],
        [4],
        [5]],

       [[6],
        [7],
        [8]]])

In [165]:
x.reshape(3,-856)#You can give any -ve number

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [174]:
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [173]:
np.diag(x) # Extract Diagonal Element

array([ 0,  5, 10, 15])

In [175]:
np.diag(x, k=2
       )

array([2, 7])

In [176]:
np.diag(x, k=1
       )

array([ 1,  6, 11])

In [177]:
np.diag(x, k=-1
       )

array([ 4,  9, 14])

In [178]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [179]:
#Create a two-dimensional array with the flattened input as a diagonal.

In [180]:
np.diagflat([[1,2], [3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [181]:
np.diagflat([1,2], 1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [182]:
#An array with ones at and below the given diagonal and zeros elsewhere.

In [186]:
np.tri(3, M=5, dtype=int)

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0]])

In [187]:
np.tri(3, M=5,k=1, dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [188]:
np.tri(3, 5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [189]:
#return a Lower triangle of an array.

In [190]:
np.tril([[1,2,3],[4,5,6],[7,8,9]], 0)

array([[1, 0, 0],
       [4, 5, 0],
       [7, 8, 9]])

In [191]:
#return Upper triangle of an array

In [194]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

In [195]:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], 0)

array([[1, 2, 3],
       [0, 5, 6],
       [0, 0, 9],
       [0, 0, 0]])

### Random number generation

In [201]:
print("Random number generation (from Uniform distribution)")
print(np.random.rand(2,3)) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note no Tuple is necessary 

Random number generation (from Uniform distribution)
[[0.27250636 0.4819428  0.08192343]
 [0.72495691 0.36504552 0.04047883]]


In [203]:
print("Return random floats in the half-open interval [0.0, 1.0).")
print(np.random.random((2,3))) # 2 by 3 matrix with random numbers ranging from 0 to 1, Note Tuple is necessary 

Return random floats in the half-open interval [0.0, 1.0).
[[0.081299   0.51213081 0.66878014]
 [0.65774549 0.57435895 0.30786783]]


In [206]:
print("Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal")
print(np.random.randn(4,3))

Numbers from Normal distribution with zero mean and standard deviation 1 i.e. standard normal
[[-1.27716824 -0.46630265 -0.1075393 ]
 [-0.78711341 -1.75246853 -0.0926918 ]
 [ 0.86952332  0.05393535  0.62752459]
 [-0.44522708  1.4796166  -0.4312393 ]]


In [211]:
print("Random integer vector:",np.random.randint(1,10)) #randint (low, high, # of samples to be drawn)
print ("\nRandom integer matrix")

Random integer vector: 8

Random integer matrix


In [212]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[78 78 17 24]
 [44 53 53 59]
 [27 83  2 30]
 [73 92 52 68]]

20 samples drawn from a dice throw: [4 4 5 3 3 3 3 6 6 6 4 1 1 2 1 3 3 4 3 4]


In [217]:
np.random.randint(1,7,size=(3,3))

array([[3, 2, 5],
       [1, 2, 3],
       [6, 2, 2]])

In [219]:
np.random.randint(1,7,size=10)

array([5, 6, 6, 2, 1, 3, 2, 2, 5, 2])

### Reshaping

In [220]:
from numpy.random import randint as ri

In [232]:
a = ri(1,100,30)
b = a.reshape(2,3,5)
c = a.reshape(5,-235)
print('Ramdomly generated samples of 30 number between 1 to 100\n','-'*80,'\n',a,'\n','-'*50,'\n')
print('Reshape to 2*3*5 matrix \n ------------------------------\n',b,'\n---------------------------\n')
print('Reshape to 5*6 matrix \n ------------------------------\n',c,'\n---------------------------\n')

Ramdomly generated samples of 30 number between 1 to 100
 -------------------------------------------------------------------------------- 
 [53 40 65 25 82 16 91 10 12 77 68 14 76  4  9 36 53  4 98 77  6 94 99 36
  4 38  6 31 16 85] 
 -------------------------------------------------- 

Reshape to 2*3*5 matrix 
 ------------------------------
 [[[53 40 65 25 82]
  [16 91 10 12 77]
  [68 14 76  4  9]]

 [[36 53  4 98 77]
  [ 6 94 99 36  4]
  [38  6 31 16 85]]] 
---------------------------

Reshape to 5*6 matrix 
 ------------------------------
 [[53 40 65 25 82 16]
 [91 10 12 77 68 14]
 [76  4  9 36 53  4]
 [98 77  6 94 99 36]
 [ 4 38  6 31 16 85]] 
---------------------------



In [228]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)

Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (5, 6)


In [233]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)


a looks like
 -------------------- 
 [53 40 65 25 82 16 91 10 12 77 68 14 76  4  9 36 53  4 98 77  6 94 99 36
  4 38  6 31 16 85] 
 --------------------

b looks like
 -------------------- 
 [[[53 40 65 25 82]
  [16 91 10 12 77]
  [68 14 76  4  9]]

 [[36 53  4 98 77]
  [ 6 94 99 36  4]
  [38  6 31 16 85]]] 
 --------------------

c looks like
 -------------------- 
 [[53 40 65 25 82 16]
 [91 10 12 77 68 14]
 [76  4  9 36 53  4]
 [98 77  6 94 99 36]
 [ 4 38  6 31 16 85]] 
 --------------------


In [240]:
A = ri(1,100,10) # Vector of random interegrs
print("\nVector of random integers\n",'-'*50,"\n",A)
print("\nHere is the sorted vector\n",'-'*50,"\n",np.sort(A))


Vector of random integers
 -------------------------------------------------- 
 [29 58  2 25  5 22 51 25 97 53]

Here is the sorted vector
 -------------------------------------------------- 
 [ 2  5 22 25 25 29 51 53 58 97]


In [241]:
np.sort(A,kind='mergesort')

array([ 2,  5, 22, 25, 25, 29, 51, 53, 58, 97])

In [251]:
M=ri(1,100,25).reshape(5,5)
print(M)
print("\nHere is the sorted matrix along each column\n",'-'*50,"\n",np.sort(M, axis=1, kind='mergesort'))
M

[[72  2  5 25 90]
 [47 32 10 65 24]
 [67 30  6 19 24]
 [25 51 83 20 51]
 [11 31 11 75 16]]

Here is the sorted matrix along each column
 -------------------------------------------------- 
 [[ 2  5 25 72 90]
 [10 24 32 47 65]
 [ 6 19 24 30 67]
 [20 25 51 51 83]
 [11 11 16 31 75]]


array([[72,  2,  5, 25, 90],
       [47, 32, 10, 65, 24],
       [67, 30,  6, 19, 24],
       [25, 51, 83, 20, 51],
       [11, 31, 11, 75, 16]])

In [252]:
print("Max of a:", M.max())
print("Max of b:", b.max())
b

Max of a: 90
Max of b: 99


array([[[53, 40, 65, 25, 82],
        [16, 91, 10, 12, 77],
        [68, 14, 76,  4,  9]],

       [[36, 53,  4, 98, 77],
        [ 6, 94, 99, 36,  4],
        [38,  6, 31, 16, 85]]])

In [254]:
print("Max of a location:", M.argmax(axis= 1 ))
print("Max of b location:", b.argmax())
print("Max of c location:", c.argmax())

Max of a location: [4 3 0 2 3]
Max of b location: 22
Max of c location: 22


### Indexing and slicing

In [372]:
arr = np.arange(0,11)
print("Array:",arr)

Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [257]:
print("Element at 7th index is:", arr[7])

Element at 7th index is: 7


In [258]:
print("Elements from 3rd to 5th index are:", arr[3:6])

Elements from 3rd to 5th index are: [3 4 5]


In [259]:
print("Elements from 3rd to 5th index are:", arr[3:6:2])

Elements from 3rd to 5th index are: [3 5]


In [260]:
print("Elements up to 4th index are:", arr[:4])
arr

Elements up to 4th index are: [0 1 2 3]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [373]:
print("Elements from last backwards are:", arr[-1::-1])#Reverse order

Elements from last backwards are: [10  9  8  7  6  5  4  3  2  1  0]


In [265]:
print("3 Elements from last backwards are:", arr[-1:7:-1])

3 Elements from last backwards are: [10  9  8]


In [275]:
arr = np.arange(0,21,2)
print("New array:",arr)

New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [276]:
print("Elements at 2nd, 4th, and 9th index are:", arr[[2,4,9]]) # Pass a list as a index to subset

Elements at 2nd, 4th, and 9th index are: [ 4  8 18]


In [285]:
import numpy as np 
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat[1:4,3:5]

Matrix of random 2-digit numbers
--------------------------------
 [[90 79 12 95 63]
 [43 99 65 76 87]
 [42 63 97 49 97]]


array([[76, 87],
       [49, 97]])

In [289]:
mat[1:3,2:5]

array([[65, 76, 87],
       [97, 49, 97]])

In [287]:
mat[0:3,[1,3]]

array([[79, 95],
       [99, 76],
       [63, 49]])

In [290]:
mat[1][1]

99

In [291]:
print("\nDouble bracket indexing\n------------------------")
print("Element in row index 1 and column index 2:", mat[1][1])
mat


Double bracket indexing
------------------------
Element in row index 1 and column index 2: 99


array([[90, 79, 12, 95, 63],
       [43, 99, 65, 76, 87],
       [42, 63, 97, 49, 97]])

In [292]:
mat[1,1]

99

In [294]:
print("\nSingle bracket with comma indexing\n----------------------------------")
print("Element in row index 1 and column index 2:", mat[1,1])
print("\nRow or column extract\n----------------------")


Single bracket with comma indexing
----------------------------------
Element in row index 1 and column index 2: 99

Row or column extract
----------------------


In [295]:
print("Entire row at index 2:", mat[2])
print("Entire column at index 3:", mat[:,3])

Entire row at index 2: [42 63 97 49 97]
Entire column at index 3: [95 76 49]


In [296]:
print("\nSubsetting sub-matrices\n--------------------------")
print("Matrix with row indices 1 and 2 and column indices 3 and 4\n", mat[1:3,3:5])


Subsetting sub-matrices
--------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4
 [[76 87]
 [49 97]]


In [297]:
print("Matrix with row indices 0 and 1 and column indices 1 and 3\n", mat[0:2,[1,3]])

Matrix with row indices 0 and 1 and column indices 1 and 3
 [[79 95]
 [99 76]]


### Subseting

In [304]:
mat=ri(1,100,15).reshape(3,5)
mat[mat>50]

array([51, 89, 76, 69, 70, 71, 54])

In [305]:
mat = np.array(ri(10,100,15)).reshape(3,5)
print("Matrix of random 2-digit numbers\n--------------------------------\n",mat)
mat>50

Matrix of random 2-digit numbers
--------------------------------
 [[46 62 83 83 32]
 [33 13 80 62 87]
 [40 49 56 32 93]]


array([[False,  True,  True,  True, False],
       [False, False,  True,  True,  True],
       [False, False,  True, False,  True]])

In [306]:
print ("Elements greater than 50\n", mat[mat>50])

Elements greater than 50
 [62 83 83 80 62 87 56 93]


### Slicing

In [317]:
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [318]:
mat_slice = mat[:2,:2]
print ("\nSliced matrix")
print(mat_slice)
print ("\nChange the sliced matrix")


Sliced matrix
[[11 12]
 [21 22]]

Change the sliced matrix


In [319]:
mat_slice[0,0] = 1000
print (mat_slice)

[[1000   12]
 [  21   22]]


In [320]:
print("\nBut the original matrix? WHOA! It got changed too!")
print(mat)


But the original matrix? WHOA! It got changed too!
[[1000   12   13]
 [  21   22   23]
 [  31   32   33]]


In [312]:
print('mat_slice[0][0] memory location',id(mat_slice[0][0]))
print('mat[0][0] memory location',id(mat[0][0]))

mat_slice[0][0] memory location 1902844737840
mat[0][0] memory location 1902844738640


In [321]:
print('mat_slice memory location',id(mat_slice))
print('mat memory location',id(mat))

mat_slice memory location 1902837736272
mat memory location 1902837769840


In [313]:
# Little different way to create a copy of the slixed matrix
print ("\nDoing it again little differently now...\n")
mat = np.array([[11,12,13],[21,22,23],[31,32,33]])
print("Original matrix")
print(mat)


Doing it again little differently now...

Original matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [314]:
mat_slice = np.array(mat[:2,:2]) # Notice the np.array command to create a new array not just slicing
print ("\nSliced matrix")
print(mat_slice)


Sliced matrix
[[11 12]
 [21 22]]


In [315]:
print ("\nChange the sliced matrix")
mat_slice[0,0] = 1000
print (mat_slice)


Change the sliced matrix
[[1000   12]
 [  21   22]]


In [316]:
print("\nBut the original matrix? NO CHANGE this time:)")
print(mat)


But the original matrix? NO CHANGE this time:)
[[11 12 13]
 [21 22 23]
 [31 32 33]]


### Universal Functions

In [322]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)



1st Matrix of random single-digit numbers
----------------------------------------
 [[3 7 8]
 [3 5 3]
 [5 3 7]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[1 8 9]
 [9 6 6]
 [5 7 5]]


In [323]:
mat1*mat2

array([[ 3, 56, 72],
       [27, 30, 18],
       [25, 21, 35]])

In [324]:
mat1 = ri(1,10,9).reshape(3,3)
mat2 = ri(1,10,9).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n----------------------------------------\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n----------------------------------------\n",mat2)


1st Matrix of random single-digit numbers
----------------------------------------
 [[4 2 8]
 [5 5 7]
 [9 5 2]]

2nd Matrix of random single-digit numbers
----------------------------------------
 [[9 5 2]
 [4 8 3]
 [6 4 4]]


In [325]:
mat1*mat2

array([[36, 10, 16],
       [20, 40, 21],
       [54, 20,  8]])

In [326]:
type(ri(1,10,9).reshape(3,3))

numpy.ndarray

In [327]:
type(np.array(ri(1,10,9)).reshape(3,3))

numpy.ndarray

In [328]:
type(np.array(ri(1,10,9)))

numpy.ndarray

In [329]:
type(ri(1,10,9))

numpy.ndarray

In [331]:
#print("\nAddition\n------------------\n", mat1+mat2)
print("\nMatrix Multiplication\n------------------\n", mat1@mat2)


Multiplication
------------------
 [[ 92  68  46]
 [107  93  53]
 [113  93  41]]


In [332]:
# Index wise multiplication
mat1*mat2

array([[36, 10, 16],
       [20, 40, 21],
       [54, 20,  8]])

In [333]:
mat1

array([[4, 2, 8],
       [5, 5, 7],
       [9, 5, 2]])

In [334]:
mat2

array([[9, 5, 2],
       [4, 8, 3],
       [6, 4, 4]])

In [335]:
print("\nAddition\n------------------\n", mat1+mat2)


Addition
------------------
 [[13  7 10]
 [ 9 13 10]
 [15  9  6]]


In [336]:
print("\nDivision\n------------------\n", mat1/0)
#print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)


Division
------------------
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


C:\Users\Sumit\anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


In [370]:
print("\nDivision\n------------------\n", mat1/mat2)


Division
------------------
 [[0.77777778 8.         1.75      ]
 [3.         2.5        1.14285714]
 [0.375      0.33333333 0.83333333]]


In [337]:
print("\nLineaer combination: 3*A - 2*B\n-----------------------------\n", 3*mat1-2*mat2)


Lineaer combination: 3*A - 2*B
-----------------------------
 [[-6 -4 20]
 [ 7 -1 15]
 [15  7 -2]]


In [338]:
print("\nAddition of a scalar (100)\n-------------------------\n", 100+mat1)


Addition of a scalar (100)
-------------------------
 [[104 102 108]
 [105 105 107]
 [109 105 102]]


In [339]:
print("\nExponentiation, matrix cubed here\n----------------------------------------\n", mat1**3)
print("\nExponentiation, sq-root using pow function\n-------------------------------------------\n",pow(mat1,3))


Exponentiation, matrix cubed here
----------------------------------------
 [[ 64   8 512]
 [125 125 343]
 [729 125   8]]

Exponentiation, sq-root using pow function
-------------------------------------------
 [[ 64   8 512]
 [125 125 343]
 [729 125   8]]


### Broadcasting

In [340]:
#NumPy operations are usually done on pairs of arrays on an element-by-element basis. 
#In the simplest case, the two arrays must have exactly the same shape.
#NumPy’s broadcasting rule relaxes this constraint when the arrays’ shapes meet certain constraints. 
#When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing 
#dimensions, and works its way forward. Two dimensions are compatible when
#they are equal, or one of them is 1

In [359]:
start = np.zeros((4,4))
start = start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [344]:
# create a rank 1 ndarray with 4 values
add_rows = np.array([1, 0, 2,5])
print(add_rows)

[1 0 2 5]


In [353]:
y = start + add_rows  # add to each row of 'start' using broadcasting
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [358]:
# create an ndarray which is 4 x 1 to broadcast across columns
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]]


In [360]:
# add to each column of 'start' using broadcasting
y = start + add_cols 
print(y)

[[100. 100. 100. 100.]
 [101. 101. 101. 101.]
 [102. 102. 102. 102.]
 [103. 103. 103. 103.]]


In [361]:
# this will just broadcast in both dimensions
add_scalar = np.array([100])  
print(start+y)

[[200. 200. 200. 200.]
 [201. 201. 201. 201.]
 [202. 202. 202. 202.]
 [203. 203. 203. 203.]]


### Array Math

In [362]:
mat1 = np.array(ri(1,10,9)).reshape(3,3)
mat2 = np.array(ri(1,10,9)).reshape(3,3)
print("\n1st Matrix of random single-digit numbers\n\n",mat1)
print("\n2nd Matrix of random single-digit numbers\n------------\n",mat2)


1st Matrix of random single-digit numbers

 [[7 8 7]
 [6 5 8]
 [3 3 5]]

2nd Matrix of random single-digit numbers
------------
 [[9 1 4]
 [2 2 7]
 [8 9 6]]


In [363]:
print("\nSq-root of 1st matrix using np\n------------------\n", np.sqrt(mat2))


Sq-root of 1st matrix using np
------------------
 [[3.         1.         2.        ]
 [1.41421356 1.41421356 2.64575131]
 [2.82842712 3.         2.44948974]]


In [364]:
print("\nExponential power of 1st matrix using np\n",'-'*50,"\n", np.exp(mat1))


Exponential power of 1st matrix using np
 -------------------------------------------------- 
 [[1096.63315843 2980.95798704 1096.63315843]
 [ 403.42879349  148.4131591  2980.95798704]
 [  20.08553692   20.08553692  148.4131591 ]]


In [365]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n", np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.84509804 0.90308999 0.84509804]
 [0.77815125 0.69897    0.90308999]
 [0.47712125 0.47712125 0.69897   ]]
[[7 8 7]
 [6 5 8]
 [3 3 5]]
[[9 1 4]
 [2 2 7]
 [8 9 6]]


In [366]:
print("\nModulo reminder using np\n",'-'*50,"\n", np.fmod(mat1,mat2))
mat1%mat2


Modulo reminder using np
 -------------------------------------------------- 
 [[7 0 3]
 [0 1 1]
 [3 3 5]]


array([[7, 0, 3],
       [0, 1, 1],
       [3, 3, 5]], dtype=int32)

In [367]:
print("\nCombination of functions by shwoing exponetial decay of a sine wave\n",'-'*70)



Combination of functions by shwoing exponetial decay of a sine wave
 ----------------------------------------------------------------------


In [369]:
A = np.linspace(0,12*np.pi,1001)
A

array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])